.PHONY: tf-init tf-fmt tf-validate tf-plan tf-apply tf-destroy

tf-init:
	docker-compose run terraform init

tf-fmt:
	docker-compose run terraform fmt

tf-validate:
	docker-compose run terraform validate

tf-plan:
	docker-compose run terraform plan

tf-apply:
	docker-compose run terraform apply --auto-approve

tf-destroy:
	docker-compose run terraform destroy --auto-approve
