.PHONY: tf-init
tf-init:
	docker-compose run terraform init

.PHONY: tf-fmt
tf-fmt:
	docker-compose run terraform fmt

.PHONY: tf-validate
	docker-compose run terraform validate

.PHONY: tf-plan
	docker-compose run terraform plan

.PHONY: tf-apply
	docker-compose run terraform apply

.PHONY: tf-destroy
	docker-compose run terraform destroy
	